Scroll Bar Fix!
qbcore-framework/qb-multicharacter pull request #190
Opened 2023-01-10 20:53 UTC by r0adra93

the buttons are at the bottom of the list
this means when you have a lot of character slots you have to scroll to the bottom to get to the button.

I made it so you don't have to scroll to see the buttons by moving the overflow and scroll buttons from the characters-list div to the characters div and I resized the characters element to allow the buttons to be viewable.

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

2023-01-11 03:52 UTC, Scones91 approved these changes
Works perfectly for me

2023-01-17 15:08 UTC, Z3rio requested changes

2023-01-17 15:08 UTC, Z3rio commented on html/style.css
> +    width: fit-contents;
`fit-content` is not a valid css "parameter" / option

2023-01-18 06:04 UTC, Z3rio commented
I'm sorry for the mis understanding, I meant that `fit-contents` not `fit-content` doesnt exist. I will fix that for you since its my fault.

2023-01-18 06:11 UTC, Z3rio commented
Only issue I saw was that the scrollbar is right next to the characters which looks quite ugly. I will go ahead and fix that aswell by simply adding some padding to `.characters`

**Before:**
![image](https://user-images.githubusercontent.com/54480523/213097632-3ce9dc32-d8d6-4725-a6d9-dd96ed566a93.png)

**After:**
![image](https://user-images.githubusercontent.com/54480523/213097684-e4d5636c-2001-45b8-8a85-18fe68f6b62c.png)

2023-01-18 06:12 UTC, Z3rio approved these changes

2023-01-18 06:13 UTC, merged